### ISSUE TITLE
Cannot reproduce the results reported in paper?

### ISSUE THREAD

**Issue by CupidJay** [ptl2r/ptl2r.github.io#5]
I am new to this area and I really appreciate you for providing such nice code. I tried to reproduce the results reported in the paper on MQ2008.

1. For ListMLE, I ran the following script
`python ptl2r.py -data MQ2008_super -dir_data ./datasets/MQ/MQ2008/ -dir_output ./outputs/ -model ListMLE `

and I get the following results in the log file
> ListMLE 5-fold cross validation scores: **nDCG@1:0.4326**, **nDCG@3:0.4574**, **nDCG@5:0.5023**, **nDCG@10:0.5824**, nDCG@20:0.3046, nDCG@50:0.1339

while in the paper the results are nDCG@1:0.4097, nDCG@3:0.4456, nDCG@5:0.4831, nDCG@10:0.5666, which are lower than the reproduced results.
 

2. For ListNet, I ran the following script
`python ptl2r.py -data MQ2008_super -dir_data ./datasets/MQ/MQ2008/ -dir_output ./outputs/ -model ListNet `

 and I get the following results 
> ListNet 5-fold cross validation scores: **nDCG@1:0.4605**, **nDCG@3:0.4839**, **nDCG@5:0.5248**, **nDCG@10:0.6062**, nDCG@20:0.3198, nDCG@50:0.1400

while in the paper the results are nDCG@1:0.4173, nDCG@3:0.4476, nDCG@5:0.4878, nDCG@10:0.5752, which are much lower than the reproduced results.

3. For WassRank, I ran the following script
`python ptl2r.py -data MQ2008_super -dir_data ./datasets/MQ/MQ2008/ -dir_output ./outputs/ -model WassRank `

 and I get the following results 
> WassRank 5-fold cross validation scores: **nDCG@1:0.4559**, **nDCG@3:0.4712**, **nDCG@5:0.5135**, **nDCG@10:0.5989**, nDCG@20:0.3112, nDCG@50:0.1333

while in the paper the results are nDCG@1:0.4384, nDCG@3:0.4594, nDCG@5:0.4987, nDCG@10:0.5833, which are lower than the reproduced results. And the results for WassRank are even worse than ListNet.

I think I might got something wrong and would you please give me some advice on reproducing the results reported in the paper? Thanks for your patience.

**Comment by laurel2935** [comment]
@CupidJay Hi, I think a possible reason is the configuration of neural networks. For example, if you run like: python ptl2r.py .... the default settings may be different from the paper setting.
